sudo: required
before_install:
  - sudo apt-get install build-essential
  - pip install --user pyyaml cpp-coveralls
  
# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - g++
  
install:
  - source install.sh

# Build steps
script:
  - mkdir build
  - cd build
  - ../deps/cmake/bin/cmake .. -DCMAKE_BUILD_TYPE=COVERAGE -DINPUT_FILE=../test/test_HODLR.cpp -DOUTPUT_EXECUTABLE=test_HODLR
  - make
  - ./test_HODLR
  - cd ${TRAVIS_BUILD_DIR}

after_success:
  - coveralls -i src
